In [3]:
import numpy as np
import torch

In [4]:
lst = [[1, 2, 3], [3, 4, 6]]
np_array = np.array(lst)
tensor = torch.tensor(np_array)
tensor.shape

torch.Size([2, 3])

In [5]:
tensor.dtype

torch.int64

In [6]:
tensor.device

device(type='cpu')

In [7]:
import torch.nn as nn

In [10]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential(nn.Linear(8, 1),
                      nn.Linear(1, 1)
                      )

output = model(input_tensor)
print(output)

tensor([[0.1609]], grad_fn=<AddmmBackward0>)


In [11]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [14]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


In [16]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
    nn.Linear(8, 1),
    nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.9898]], grad_fn=<SigmoidBackward0>)


In [18]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 3),
    nn.Linear(3, 12),
    nn.Linear(12, 8),
    nn.Linear(8, 1),
)

output = model(input_tensor)
print(output)

tensor([[-1.1091]], grad_fn=<AddmmBackward0>)


In [19]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
    nn.Linear(11, 20),
    nn.Linear(20, 12),
    nn.Linear(12, 6),
    nn.Linear(6, 4),
    nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.1704, 0.2976, 0.1553, 0.3766]], grad_fn=<SoftmaxBackward0>)


In [20]:
# converts weights to float
input_tensor.double()

tensor([[ 3.,  4.,  6.,  7., 10., 12.,  2.,  3.,  6.,  8.,  9.]],
       dtype=torch.float64)

In [22]:
import torch.nn.functional as F

y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(1), num_classes=num_classes)
one_hot_pytorch

tensor([0, 1, 0])

In [29]:
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor([2]), num_classes=4)

criterion = nn.CrossEntropyLoss()
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


In [30]:
criterion(one_hot_label.double(), scores.double())

tensor(14.7288, dtype=torch.float64)

In [34]:
criterion = nn.CrossEntropyLoss()
preds = torch.tensor([[-1.7153, 0.3799]], requires_grad=True)
target = torch.tensor([[1., 0.]])

weight = torch.tensor([[-1.8072, -2.9975, -1.2635, 1.2220, 1.3340, -0.4344, 1.2662, -0.7905,
                        1.2092],
                       [-0.1426, 1.0565, 1.1914, 0.4710, -0.8984, 0.0105, -1.1036, 1.6828,
                        -0.4550]], requires_grad=True)
bias = torch.tensor([-1.0820, -0.1427], requires_grad=True)

# Calculate the loss
loss = criterion(preds, target)

# Compute the gradients of the loss
loss.backward()

# Display gradients of the weight and bias tensors in order
print(weight.grad)
print(bias.grad)

None
None


In [39]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Sigmoid(),
                      nn.Linear(8, 2))

# Access the weight of the first linear layer
weight_0 = model[0].weight
print(weight_0)
# Access the bias of the second linear layer
bias_1 = model[2].bias
print(bias_1)

Parameter containing:
tensor([[ 0.1104, -0.2084,  0.2161, -0.0777, -0.1249, -0.1602,  0.1975,  0.0779,
          0.1963,  0.0383,  0.1426, -0.2423, -0.1312, -0.2143, -0.2388, -0.1544],
        [ 0.1174,  0.0970, -0.0619, -0.2032, -0.0854,  0.1508, -0.1726, -0.1940,
          0.1344, -0.0907, -0.0795,  0.0772,  0.1341, -0.0548, -0.0347,  0.0466],
        [-0.0164, -0.0295, -0.1931, -0.0184,  0.0613,  0.1675, -0.0347,  0.1912,
         -0.0741,  0.1185, -0.0195,  0.1501,  0.2221, -0.0139,  0.0750, -0.0704],
        [ 0.2296,  0.0916, -0.0630, -0.1872, -0.1400,  0.2172, -0.2253,  0.0272,
          0.0386,  0.0384,  0.1800, -0.0736,  0.2057, -0.1808, -0.2305, -0.2063],
        [ 0.0166,  0.1517,  0.0709, -0.1940,  0.0069,  0.0053,  0.0383, -0.1530,
          0.0742,  0.1176,  0.1786,  0.0956, -0.0290,  0.0522,  0.1287,  0.0394],
        [-0.0481,  0.1816,  0.1736,  0.0006, -0.0176, -0.1875, -0.1685, -0.2057,
          0.0290,  0.0378, -0.2135,  0.1526, -0.1997,  0.1362, -0.2145,  0.1709],


In [40]:
import torch.optim as optim

# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [42]:
loss = criterion(preds, target)
loss.backward()

In [45]:
optimizer.step()

None


In [46]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [51]:
y_hat = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y - y_hat) ** 2)
print(mse_numpy)
# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_hat).double(), torch.tensor(y).double())
print(mse_pytorch)

81.0
tensor(81., dtype=torch.float64)


In [52]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

tensor(0.)


In [53]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

tensor(-0.1000)


In [59]:
model = nn.Sequential(nn.Linear(16, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))
total = 0
for param in model.parameters():
    total += param.numel()
total

81

![Learning Rate and Momentum](lr_vs_momentum.png "Learning Rate and Momentum")

In [61]:
for name, param in model.named_parameters():
    print(name)

0.weight
0.bias
1.weight
1.bias
2.weight
2.bias


Choosing which layer to freeze is an empirical process but a good rule of thumb is to start with the first layers and go deeper.

In [62]:
for name, param in model.named_parameters():

    # Check if the parameters belong to the first layer
    if name == '0.weight' or name == '0.bias':
        # Freeze the parameters
        param.requires_grad = False

    # Check if the parameters belong to the second layer
    if name == '1.weight' or name == '1.bias':
        # Freeze the parameters
        param.requires_grad = False

In [69]:
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Use uniform initialization for layer0 and layer1 weights
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model = nn.Sequential(layer0, layer1)
print(layer0.weight.min(), layer0.weight.max())
print(layer1.weight.min(), layer1.weight.max())

tensor(0.0021, grad_fn=<MinBackward1>) tensor(0.9979, grad_fn=<MaxBackward1>)
tensor(0.0002, grad_fn=<MinBackward1>) tensor(0.9999, grad_fn=<MaxBackward1>)


In [71]:
import numpy as np
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

# Convert arrays to PyTorch tensors
torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

# Create a TensorDataset from two tensors
dataset = TensorDataset(torch_features, torch_target)

# Return the last element of this dataset
print(dataset[-1])

(tensor([0.2368, 0.2278, 0.4657, 0.4628, 0.2790, 0.1873, 0.8502, 0.4834],
       dtype=torch.float64), tensor([0.2075], dtype=torch.float64))


In [72]:
import pandas as pd

dataframe = pd.read_csv('water_potability.csv')
dataframe

ph  Hardness    Solids  Chloramines   Sulfate  Conductivity  \
0     0.587349  0.577747  0.386298     0.568199  0.647347      0.292985   
1     0.643654  0.441300  0.314381     0.439304  0.514545      0.356685   
2     0.388934  0.470876  0.506122     0.524364  0.561537      0.142913   
3     0.725820  0.715942  0.506141     0.521683  0.751819      0.148683   
4     0.610517  0.532588  0.237701     0.270288  0.495155      0.494792   
...        ...       ...       ...          ...       ...           ...   
2006  0.636224  0.580511  0.277748     0.418063  0.522486      0.342184   
2007  0.470143  0.548826  0.301347     0.538273  0.498565      0.231359   
2008  0.817826  0.087434  0.656389     0.670774  0.369089      0.431872   
2009  0.424187  0.464092  0.459656     0.541633  0.615572      0.388360   
2010  0.322425  0.492891  0.841409     0.492136  0.656047      0.588709   

      Organic_carbon  Trihalomethanes  Turbidity  Potability  
0           0.654522         0.795029   0.630115           0  
1           0.377248         0.202914   0.520358           0  
2           0.249922         0.401487   0.219973           0  
3           0.467200         0.658678   0.242428           0  
4           0.409721         0.469762   0.585049           0  
...              ...              ...        ...         ...  
2006        0.310364         0.402799   0.627156           1  
2007        0.565061         0.175889   0.395061           1  
2008        0.563265         0.285745   0.578674           1  
2009        0.397780         0.449156   0.440004           1  
2010        0.471422         0.503458   0.591867           1  

[2011 rows x 10 columns]

In [74]:
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].to_numpy()).float()
target = torch.tensor(dataframe['Potability'].to_numpy()).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

In [75]:
from torch.utils.data import DataLoader

# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
x, y = next(iter(dataloader))

In [76]:
# Create a model using the nn.Sequential API
model = nn.Sequential(
    nn.Linear(4, 10),
    nn.Linear(10, 1)
)
output = model(features)
print(output)

tensor([[0.3716],
        [0.4196],
        [0.4039],
        ...,
        [0.3880],
        [0.3829],
        [0.3454]], grad_fn=<AddmmBackward0>)


In [83]:
mask_dataset = pd.read_pickle('masks_dataset.pickle')
mask_dataset

(array([[[[0.38053016, 0.35004572, 0.38045538],
          [0.49561382, 0.45045635, 0.47310239],
          [0.5744727 , 0.51869527, 0.53720113],
          ...,
          [0.34580102, 0.29482917, 0.30817478],
          [0.28303221, 0.24503852, 0.26706514],
          [0.15621841, 0.14549615, 0.18887831]],
 
         [[0.44942444, 0.40002741, 0.41653014],
          [0.56823385, 0.50350932, 0.51621795],
          [0.61456819, 0.54212599, 0.55860702],
          ...,
          [0.40559703, 0.35699659, 0.36157709],
          [0.39955874, 0.35576992, 0.36392419],
          [0.22050038, 0.19371628, 0.2253609 ]],
 
         [[0.59694617, 0.52626227, 0.53245013],
          [0.62542287, 0.5513043 , 0.5661661 ],
          [0.62773799, 0.55528255, 0.57796426],
          ...,
          [0.43312883, 0.38273693, 0.38574492],
          [0.44604589, 0.40381404, 0.40859798],
          [0.32149855, 0.28387212, 0.29545527]],
 
         ...,
 
         [[0.51461386, 0.46347499, 0.45039961],
          [0.49280

In [90]:
mask_dataset[0], mask_dataset[1]

(array([[[[0.38053016, 0.35004572, 0.38045538],
          [0.49561382, 0.45045635, 0.47310239],
          [0.5744727 , 0.51869527, 0.53720113],
          ...,
          [0.34580102, 0.29482917, 0.30817478],
          [0.28303221, 0.24503852, 0.26706514],
          [0.15621841, 0.14549615, 0.18887831]],
 
         [[0.44942444, 0.40002741, 0.41653014],
          [0.56823385, 0.50350932, 0.51621795],
          [0.61456819, 0.54212599, 0.55860702],
          ...,
          [0.40559703, 0.35699659, 0.36157709],
          [0.39955874, 0.35576992, 0.36392419],
          [0.22050038, 0.19371628, 0.2253609 ]],
 
         [[0.59694617, 0.52626227, 0.53245013],
          [0.62542287, 0.5513043 , 0.5661661 ],
          [0.62773799, 0.55528255, 0.57796426],
          ...,
          [0.43312883, 0.38273693, 0.38574492],
          [0.44604589, 0.40381404, 0.40859798],
          [0.32149855, 0.28387212, 0.29545527]],
 
         ...,
 
         [[0.51461386, 0.46347499, 0.45039961],
          [0.49280

In [140]:
mask_dataset[0].shape, mask_dataset[1].shape

((355, 32, 32, 3), (355,))

In [214]:
import torchmetrics
import torchvision.transforms as transforms

features, target = mask_dataset
# Create a dataset from the two generated tensors
dataset = TensorDataset(torch.tensor(features).float(), torch.tensor(target).float())
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

mean = (features / 255).reshape(3,-1).mean(axis=1)
std = (features / 255).reshape(3,-1).std(axis=1)

model = nn.Sequential(
    # transforms.Normalize(list(mean), list(std)),
    nn.Flatten(start_dim=1, end_dim=-1),
    nn.Linear(3072, 3)
)
print(model)

metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for data in dataloader:
    features, labels = data
    outputs = model(features)
    # Calculate accuracy over the batch
    acc = metric(outputs.argmax(dim=-1), labels)

# Calculate accuracy over the whole epoch
acc = metric.compute()

# Reset the metric for the next epoch 
metric.reset()

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=3072, out_features=3, bias=True)
)


In [215]:
acc

tensor(0.4254)

In [218]:
model = nn.Sequential(
    nn.Linear(11,16),
    nn.ReLU(),
    nn.Dropout(p=0.8)
)
model(input_tensor)

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000, 36.9740,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
       grad_fn=<MulBackward0>)